
# These variables are build-specific and should be passed via the --set parameter.
nginx:
  image: 'you need to pass in a value for nginx.image to your helm chart'
drupal:
  image: 'you need to pass in a value for drupal.image to your helm chart'
  env:
  #these are added to drupal environment
    PHP_FPM_CLEAR_ENV: "no"

mariadb:
  master:
    persistence:
      storageClass: standard
  replication:
    enabled: false
  rootUser:
    password: "{{ randAlphaNum 10 }}" # pass in a value to your helm chart to override this
  db:
    name: drupal
    user: drupal
    password: "{{ randAlphaNum 10 }}" # pass in a value to your helm chart to override this

ingress:
  hostname: "35.201.117.136.nip.io"
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: your-static-ip-name

secrets:
    hashsalt: "template-hash-salt"
