apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cron
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  backOffLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drupal-cron
            image: "{{ .Values.drupal.image }}"
            command:
            - drush
            - cron
{{ include "drupal.drupal-container" . | indent 12 }}
          imagePullSecrets:
          - name: gcr
          volumes:
{{ include "drupal.drupal-files-volume" . | indent 10 }}
          restartPolicy: OnFailure
