{{- if eq .Values.publicFiles.storageClassName "silta-shared"}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-public-files
  labels:
    name: {{ .Release.Name }}-public-files
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.publicFiles.storage }}
  storageClassName: {{ .Values.publicFiles.storageClassName }}
  {{- if .Values.publicFiles.csiDriverName }}
  csi:
    driver: {{ .Values.publicFiles.csiDriverName }}
    volumeHandle: {{ .Release.Name }}-public-files
    volumeAttributes:
      remotePathSuffix: /{{ .Release.Namespace }}/{{ .Values.environmentName }}/public-files
  {{- end }} 
---
{{- end }} 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-public-files
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.publicFiles.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.publicFiles.storage }}
---
{{- if .Values.privateFiles.enabled }}
{{- if eq .Values.privateFiles.storageClassName "silta-shared"}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-private-files
  labels:
    name: {{ .Release.Name }}-private-files
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.privateFiles.storage }}
  storageClassName: {{ .Values.privateFiles.storageClassName }}
  {{- if .Values.privateFiles.csiDriverName }}
  csi:
    driver: {{ .Values.privateFiles.csiDriverName }}
    volumeHandle: {{ .Release.Name }}-private-files
    volumeAttributes:
      remotePathSuffix: /{{ .Release.Namespace }}/{{ .Values.environmentName }}/private-files
  {{- end }}
---
{{- end }} 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-private-files
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.privateFiles.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.privateFiles.storage }}
{{- end }}
---
{{- if .Values.referenceData.enabled }}
{{- if eq .Values.referenceData.referenceEnvironment .Values.environmentName }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-reference-data
  labels:
    name: {{ .Release.Name }}-reference-data
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.referenceData.storage }}
  storageClassName: {{ .Values.referenceData.storageClassName }}
  {{- if .Values.referenceData.csiDriverName }}
  csi:
    driver: {{ .Values.referenceData.csiDriverName }}
    volumeHandle: {{ .Release.Name }}-reference-data
    volumeAttributes:
      remotePathSuffix: /{{ .Release.Namespace }}/{{ .Values.environmentName }}/reference-data
  {{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "drupal.referenceEnvironment" . }}-reference-data
  labels:
    app: {{ .Values.app | quote }}
    release: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.referenceData.storageClassName }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.referenceData.storage }}
{{- end }}
{{- end }}
---
{{- if .Values.shell.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-shell-keys
  labels:
    {{- include "drupal.release_labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50M
{{- end }}