apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-postinstall"
  labels:
    app: postinstall
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postinstall
        command: ["/bin/sh", "-c"]
        args:
        - {{ .Values.commands.postinstall | quote }}
{{ include "drupal.drupal-container" . | indent 8 }}
      {{- if .Values.secrets.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.secrets.imagePullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      volumes:
{{ include "drupal.drupal-files-volume" . | indent 6 }}
