apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-postinstall"
  labels:
    app: postinstall
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: postinstall
        command: ["/bin/sh", "-c"]
        args:
        - cd web;
          bootstrapped=$(drush status --field=bootstrap);
          if [[ $bootstrapped = *'Success'* ]]; then drush updatedb -n; drush config-import -n; drush entity-updates -n;
          else drush site-install -n config_installer; conf_count=$(ls ../config/sync/ | wc -l); if [ $conf_count -lt 2 ]; then drush site-install minimal -y; fi; fi;
{{ include "drupal.drupal-container" . | indent 8 }}
      imagePullSecrets:
      - name: gcr
      volumes:
{{ include "drupal.drupal-files-volume" . | indent 6 }}